name: "🌐 Localization/Translation issue"
description: Report incorrect translations.
labels:
- Issue-Bug
- Area-Localization
- Issue-Translation
- Needs-Triage
body:
- type: markdown
  attributes:
    value: Please make sure to [search for existing issues](https://github.com/iomismo/DocToys/issues) before filing a new one!
- type: input
  attributes:
    label: Rabazco DocToys version
    placeholder: 0.70.0
    description: Look at Settings
  validations:
    required: true
- type: dropdown
  attributes:
    label: Utility with translation issue
    options:
    - General
    - Text Editor
    - Open XML Tools
    - PDF Merge
    - PDF Split
    - Settings
  validations:
    required: true
- type: input
  attributes:
    label: 🌐 Language affected
    placeholder: "German"
  validations:
    required: true
- type: textarea
  attributes: 
    label: ❌ Actual phrase(s)
    placeholder: What is there? Please include a screenshot as that is extremely helpful.
  validations:
    required: true
- type: textarea
  attributes: 
    label: ✔️ Expected phrase(s)
    placeholder: What was expected?
  validations:
    required: true
- type: textarea
  attributes:
    label: ℹ Why is the current translation wrong
    placeholder: Why do you feel this is incorrect?
  validations:
    required: true
